// Standalone HTML report. Self-contained: no external scripts, no CDN, no
// fonts. Drop the file into a static host or attach to an email digest.

import type { Finding, Severity } from "../../core/detectors/types.js";
import { summarize } from "./format.js";

const SEVERITY_COLOR: Record<Severity, string> = {
  critical: "#b91c1c",
  high: "#dc2626",
  medium: "#d97706",
  low: "#0891b2",
  info: "#6b7280",
};

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function formatHtml(findings: Finding[], opts: { title?: string } = {}): string {
  const title = opts.title ?? "agent-review report";
  const summary = summarize(findings);

  const findingsHtml = findings
    .map((f) => {
      const color = SEVERITY_COLOR[f.severity];
      return `<article class="finding">
  <header>
    <span class="badge" style="background:${color}">${esc(f.severity)}</span>
    <code class="det-id">${esc(f.detectorId)}</code>
    <span class="title">${esc(f.title)}</span>
    <span class="confidence">(${esc(f.confidence)} confidence)</span>
  </header>
  <p class="path"><strong>${esc(f.file)}</strong>:${f.line}</p>
  <p class="msg">${esc(f.message)}</p>
  ${f.excerpt ? `<pre><code>${esc(f.excerpt)}</code></pre>` : ""}
  ${f.rationale ? `<p class="rationale"><em>Rationale:</em> ${esc(f.rationale)}</p>` : ""}
  ${f.suggestion?.kind === "text-only" && f.suggestion.text ? `<p class="suggestion"><strong>Suggestion:</strong> ${esc(f.suggestion.text)}</p>` : ""}
</article>`;
    })
    .join("\n");

  const summaryRows = (["critical", "high", "medium", "low", "info"] as Severity[])
    .filter((s) => summary.bySeverity[s] > 0)
    .map(
      (s) =>
        `<tr><td><span class="badge" style="background:${SEVERITY_COLOR[s]}">${s}</span></td><td>${summary.bySeverity[s]}</td></tr>`
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${esc(title)}</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, system-ui, sans-serif; max-width: 960px; margin: 32px auto; padding: 0 16px; }
  h1 { margin: 0 0 8px; }
  .meta { color: #6b7280; margin-bottom: 24px; }
  table { border-collapse: collapse; margin-bottom: 24px; }
  td { padding: 4px 16px 4px 0; }
  .badge { color: #fff; padding: 2px 8px; border-radius: 4px; font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; }
  .det-id { color: #7c3aed; font-weight: 600; margin: 0 8px; }
  .title { font-weight: 600; }
  .confidence { color: #6b7280; font-size: 12px; margin-left: 8px; }
  .finding { border-left: 3px solid #e5e7eb; padding: 12px 16px; margin-bottom: 16px; background: #f9fafb; border-radius: 4px; }
  .path { color: #4b5563; margin: 8px 0 4px; font-size: 13px; }
  .msg { margin: 4px 0 12px; }
  pre { background: #1f2937; color: #f3f4f6; padding: 12px; border-radius: 4px; overflow-x: auto; font-size: 12px; margin: 0 0 8px; }
  .suggestion { color: #047857; }
  .rationale { color: #6b7280; font-size: 13px; }
  @media (prefers-color-scheme: dark) {
    body { background: #111827; color: #f3f4f6; }
    .finding { background: #1f2937; border-left-color: #374151; }
    .path { color: #d1d5db; }
    .meta { color: #9ca3af; }
    .confidence { color: #9ca3af; }
  }
</style>
</head>
<body>
<h1>${esc(title)}</h1>
<p class="meta">${summary.total} findings · generated ${new Date().toISOString()}</p>
<table>
  <tbody>
    ${summaryRows || '<tr><td colspan="2"><em>No findings.</em></td></tr>'}
  </tbody>
</table>
${findingsHtml}
<footer style="margin-top:48px;color:#6b7280;font-size:12px;">
  Report generated by <a href="https://github.com/agent-review/agent-review">agent-review</a>.
</footer>
</body>
</html>`;
}
